configfile: "config/config.yaml"

include: "rules/common.smk"
include: "rules/data/clinvar.smk"
include: "rules/data/complex_traits.smk"
include: "rules/data/eqtl.smk"
include: "rules/data/gnomad.smk"
include: "rules/data/ldscore.smk"
include: "rules/data/mendelian_traits.smk"
include: "rules/data/simulated.smk"
include: "rules/features/aidodna.smk"
include: "rules/features/alphagenome.smk"
include: "rules/features/cadd.smk"
include: "rules/features/caduceus.smk"
include: "rules/features/conservation.smk"
include: "rules/features/dist.smk"
include: "rules/features/enformer.smk"
include: "rules/features/evo2.smk"
include: "rules/features/gpn.smk"
include: "rules/features/gpn_msa.smk"
include: "rules/features/grelu.smk"
include: "rules/features/hyenadna.smk"
include: "rules/features/maf.smk"
include: "rules/features/nucleotide_transformer.smk"
include: "rules/features/sei.smk"
include: "rules/features/specieslm.smk"
include: "rules/model.smk"


rule all:
    input:
        expand(
            "results/dataset/{dataset}/features/{features}.parquet",
            dataset=config["datasets"],
            features=[
                #"Enformer_L2",
                #"Borzoi_L2",
                #"CADD",
                #"GPN-MSA_LLR",
                #"GPN-MSA_InnerProducts",
                #"GPN-MSA_Embeddings",

                #"NucleotideTransformer_LLR",
                #"NucleotideTransformer_InnerProducts",

                #"GPN_final_LLR",
                #"GPN_final_Embeddings",
                #"GPN_final_InnerProducts",

                #"HyenaDNA_LLR",
                #"HyenaDNA_InnerProducts",

                #"Caduceus_LLR",
                #"Caduceus_InnerProducts",
                #"Caduceus_Embeddings",

                "AlphaGenome",
            ],
        )


rule glm_unsupervised:
    input:
        expand(
            "results/dataset/{dataset}/{metric}/{subset}/{model}_{score}.csv",
            dataset=config["datasets"],
            metric=[
                #"AUPRC_by_chrom_weighted_average",
                #"AUROC_by_chrom_weighted_average",
                #"AUPRC",
                "OR",
                "OR_v2",
                "OR_10%",
            ],
            subset=["all"],
            model=[
                #"GPN_final",
                #"NucleotideTransformer",
                #"HyenaDNA",
                #"Caduceus",
                "GPN-MSA",
                #"SpeciesLM",
                #"AIDO.DNA",
                #"evo2_1b_base",
                #"evo2_7b",
                "evo2_40b",
            ],
            score=[
                "LLR.minus.score",
                "absLLR.plus.score",
                #"Embeddings.plus.euclidean_distance",
                #"Embeddings.plus.cosine_distance",
                #"Embeddings.minus.inner_product",
            ],
        ),


rule other_unsupervised:
    input:
        expand(
            "results/dataset/{dataset}/{metric}/{subset}/{model}.csv",
            dataset=config["datasets"],
            metric=[
            #    "AUPRC_by_chrom_weighted_average",
            #    "AUROC_by_chrom_weighted_average",
            #    "AUPRC",
                "OR",
                "OR_v2",
                "OR_10%",
            ],
            subset=["all"],
            model=[
                "CADD.plus.RawScore",
                "Enformer_L2_L2.plus.all",
                "Borzoi_L2_L2.plus.all",
                "Sei.plus.seqclass_max_absdiff",
                "phyloP-100v.plus.score",
                "phyloP-241m.plus.score",
                "phastCons-43p.plus.score",
            ],
        ),


rule general_supervised:
    input:
        expand(
            "results/dataset/{dataset}/{metric}/{subset}/{feature_set}.{classifier}.chrom.csv",
            dataset=config["datasets"],
            metric=[
                "AUPRC_by_chrom_weighted_average",
                "AUROC_by_chrom_weighted_average",
            ],
            subset=["all"],
            feature_set=[
                #"CADD",
                #"Enformer",
                #"Borzoi",
                #"GPN-MSA",
                #"GPN_final",
                #"NucleotideTransformer",
                #"HyenaDNA",
                #"Caduceus",
                #"Sei",
                #"SpeciesLM",
                #"AIDO.DNA",
                #"evo2_1b_base",
                #"evo2_7b",
                "evo2_40b",
                #"CADD+GPN-MSA",
                #"CADD+Borzoi",
                #"GPN-MSA+Borzoi",
                #"CADD+GPN-MSA+Borzoi",
            ],
            classifier=[
                "LogisticRegression",
            ]
        ),
        #expand(
        #    "results/dataset/{dataset}/metrics_by_chrom_weighted_average/{subset}/{feature_set}.{classifier}.chrom.subset_from_all.csv",
        #    dataset=config["datasets"],
        #    subset=config["consequence_subsets"],
        #    feature_set=[
        #        "CADD",
        #        "Borzoi",
        #        "GPN-MSA",
        #        "CADD+GPN-MSA+Borzoi",
        #        "CADD+GPN-MSA_LLR+Borzoi_L2_L2",
        #    ],
        #    classifier=[
        #        "LogisticRegression",
        #    ]
        #),


rule select_mendelian_traits:
    input:
        expand(
            "results/dataset/{dataset}/metrics_by_chrom_weighted_average/{subset}/{model}.csv",
            dataset=["mendelian_traits_matched_9"],
            subset=select_omim_traits + config["consequence_subsets"],
            model=[
                "CADD.plus.RawScore",
                "Borzoi_L2_L2.plus.all",
                "GPN-MSA_LLR.minus.score",
            ],
        ),
        expand(
            "results/dataset/{dataset}/metrics_by_chrom_weighted_average/{subset}/{feature_set}.{classifier}.chrom.subset_from_all.csv",
            dataset=["mendelian_traits_matched_9"],
            subset=select_omim_traits,
            feature_set=[
                "CADD",
                "Borzoi",
                "GPN-MSA",
                "CADD+GPN-MSA+Borzoi",
                "CADD+GPN-MSA_LLR+Borzoi_L2_L2",
            ],
            classifier=[
                "LogisticRegression",
            ]
        ),


rule select_complex_traits:
    input:
        expand(
            "results/dataset/{dataset}/metrics_by_chrom_weighted_average/{subset}/{model}.csv",
            dataset=["complex_traits_matched_9"],
            subset=(
                select_gwas_traits +
                config["consequence_subsets"] +
                ["disease", "non_disease"]
            ),
            model=[
                "CADD.plus.RawScore",
                "Borzoi_L2_L2.plus.all",
                "GPN-MSA_absLLR.plus.score",
            ],
        ),
        #expand(
        #    "results/dataset/{dataset}/metrics_by_chrom_weighted_average/{subset}/{feature_set}.{classifier}.chrom.subset_from_all.csv",
        #    dataset=["complex_traits_matched_9"],
        #    subset=(
        #        select_gwas_traits +
        #        ["disease", "non_disease"]
        #    ),
        #    feature_set=[
        #        "CADD",
        #        "Borzoi",
        #        "GPN-MSA",
        #        "CADD+GPN-MSA+Borzoi",
        #    ],
        #    classifier=[
        #        "LogisticRegression",
        #    ]
        #),
        #expand(
        #    "results/dataset/{dataset}/metrics_by_chrom_weighted_average/{subset}/{feature_set}.{classifier}.chrom.csv",
        #    dataset=["complex_traits_matched_9"],
        #    subset=["Height", "Mono"],
        #    feature_set=[
        #        "CADD",
        #        "Borzoi",
        #        "GPN-MSA",
        #        "CADD+GPN-MSA+Borzoi",
        #    ],
        #    classifier=[
        #        "LogisticRegression",
        #    ]
        #),


rule interpretation_cadd:
    input:
        expand(
            "results/dataset/{dataset}/unsupervised_metrics/{subset}/{features}.csv",
            dataset=config["datasets"],
            subset=["all"],
            features=["CADD"],
        ),


rule interpretation_borzoi:
    input:
        expand(
            "results/dataset/{dataset}/unsupervised_metrics/{subset}/{features}.csv",
            dataset=["mendelian_traits_matched_9"],
            subset=[
                "613985",
                "306900",
                "143890",
                "614743",
                "250250",
            ],
            features=[
                "Borzoi_L2",
            ],
        ),
        expand(
            "results/dataset/{dataset}/unsupervised_metrics/{subset}/{features}.csv",
            dataset=["complex_traits_matched_9"],
            subset=[
                "Height",
                "Mono",
                "HbA1c",
                "HDLC",
                "Alb",
                "DVT",
            ],
            features=[
                "Borzoi_L2",
            ],
        ),
        expand(
            "results/dataset/{dataset}/metrics_by_chrom_weighted_average/{subset}/Borzoi_L2_L2.plus.{assay}.csv",
            dataset=config["datasets"],
            subset=config["consequence_subsets"] + ["all"],
            assay=["RNA", "CAGE", "ATAC", "DNASE", "CHIP"],
        ),


rule ensemble_light:
    input:
        expand(
            "results/dataset/{dataset}/metrics_by_chrom_weighted_average/{subset}/{feature_set}.{classifier}.chrom.csv",
            dataset=config["datasets"],
            subset=["all"],
            feature_set=[
                "CADD+GPN-MSA_LLR",
                "CADD+Borzoi_L2_L2",
                "CADD+GPN-MSA_LLR+Borzoi_L2_L2",
            ],
            classifier=[
                "LogisticRegression",
            ]
        ),


rule extra_unsupervised:
    input:
        expand(
            "results/dataset/mendelian_traits_all/AUPRC/all/{model}.csv",
            model=[
                "CADD.plus.RawScore",
                "GPN-MSA_LLR.minus.score",
                "phyloP-100v.plus.score",
                "phyloP-241m.plus.score",
                "phastCons-43p.plus.score",
            ],
        ),
        expand(
            "results/dataset/complex_traits_all/AUPRC/maf_match/{model}.csv",
            model=[
                "CADD.plus.RawScore",
                "GPN-MSA_absLLR.plus.score",
                "phyloP-100v.plus.score",
                "phyloP-241m.plus.score",
                "phastCons-43p.plus.score",
            ],
        ),


rule no_cadd_overlap:
    input:
        expand(
            "results/dataset/{dataset}/{metric}/{subset}/{model}.csv",
            dataset=config["datasets"],
            metric=["AUPRC_by_chrom_weighted_average"],
            subset=["no_cadd_overlap"],
            model=[
                #"CADD.plus.RawScore",
                #"Borzoi_L2_L2.plus.all",
                #"Enformer_L2_L2.plus.all",
                #"GPN-MSA_LLR.minus.score",
                #"GPN-MSA_absLLR.plus.score",
                #"GPN_final_LLR.minus.score",
                #"GPN_final_Embeddings.plus.euclidean_distance",
                #"Sei.plus.seqclass_max_absdiff",
                #"NucleotideTransformer_Embeddings.plus.euclidean_distance",
                #"NucleotideTransformer_Embeddings.minus.inner_product",
                #"HyenaDNA_Embeddings.minus.inner_product",
                #"Caduceus_Embeddings.plus.euclidean_distance",
                #"Caduceus_Embeddings.minus.inner_product",
                "SpeciesLM_Embeddings.plus.euclidean_distance",
                "AIDO.DNA_Embeddings.minus.inner_product",

                "evo2_1b_base_Embeddings.plus.euclidean_distance",
                "evo2_1b_base_Embeddings.minus.inner_product",

                "evo2_7b_LLR.minus.score",
                "evo2_7b_Embeddings.plus.euclidean_distance",

                "evo2_40b_LLR.minus.score",
                "evo2_40b_absLLR.plus.score",

                "phyloP-100v.plus.score",
                "phyloP-241m.plus.score",
                "phastCons-43p.plus.score",
            ],
        ),
        expand(
            "results/dataset/{dataset}/{metric}/{subset}/{feature_set}.{classifier}.chrom.subset_from_all.csv",
            dataset=config["datasets"],
            metric=["AUPRC_by_chrom_weighted_average"],
            subset=["no_cadd_overlap"],
            feature_set=[
                #"CADD",
                #"Borzoi",
                #"Enformer",
                #"GPN-MSA",
                #"GPN_final",
                #"Sei",
                #"NucleotideTransformer",
                #"HyenaDNA",
                #"Caduceus",
                "SpeciesLM",
                "AIDO.DNA",
                "evo2_1b_base",
                "evo2_7b",
                "evo2_40b",
            ],
            classifier=[
                "LogisticRegression",
            ]
        ),


rule eqtl_overlap:
    input:
        expand(
            "results/dataset/{dataset}/{metric}/{subset}/{model}.csv",
            dataset=["complex_traits_matched_9"],
            metric=["AUPRC_by_chrom_weighted_average"],
            subset=["yes_eqtl_overlap", "no_eqtl_overlap"],
            model=[
                "CADD.plus.RawScore",
                "Borzoi_L2_L2.plus.all",
                "GPN-MSA_absLLR.plus.score",
            ],
        ),
        expand(
            "results/dataset/{dataset}/{metric}/{subset}/{feature_set}.{classifier}.chrom.subset_from_all.csv",
            dataset=["complex_traits_matched_9"],
            metric=["AUPRC_by_chrom_weighted_average"],
            subset=["yes_eqtl_overlap", "no_eqtl_overlap"],
            feature_set=[
                "CADD",
                "Borzoi",
                "GPN-MSA",
                "CADD+GPN-MSA+Borzoi",
            ],
            classifier=[
                "LogisticRegression",
            ]
        ),


rule glm_promoter_consequence:
    input:
        expand(
            "results/dataset/mendelian_traits_matched_9/AUPRC_by_chrom_weighted_average/{subset}/{model}.csv",
            subset=config["consequence_subsets"],
            model=[
                "GPN_final_LLR.minus.score",
                "GPN_final.LogisticRegression.chrom.subset_from_all",
            ],
        ),
        expand(
            "results/dataset/complex_traits_matched_9/AUPRC_by_chrom_weighted_average/{subset}/{model}.csv",
            subset=config["consequence_subsets"],
            model=[
                "GPN_final_Embeddings.plus.euclidean_distance",
                "GPN_final.LogisticRegression.chrom.subset_from_all",
            ],
        ),


rule mendelian_maf_ablation:
    input:
        expand(
            "results/dataset/mendelian_traits_v21_matched_9/AUPRC_by_chrom_weighted_average/all/{model}.csv",
            subset=config["consequence_subsets"],
            model=[
                "GPN-MSA_LLR.minus.score",
                "CADD.plus.RawScore",
                "Borzoi_L2_L2.plus.all",
                "GPN-MSA.LogisticRegression.chrom",
                "CADD.LogisticRegression.chrom",
                "Borzoi.LogisticRegression.chrom",
            ],
        ),


rule additional_complex_traits_experiments:
    input:
        expand(
            "results/dataset/complex_traits_matched_9/AUPRC_by_chrom_weighted_average/{subset}/{model}.csv",
            subset=[
                "pip_0.99",
                "pip_0.999",
                "pleiotropy_yes",
                "pleiotropy_no",
            ],
            model=[
                "GPN-MSA_absLLR.plus.score",
                "CADD.plus.RawScore",
                "Borzoi_L2_L2.plus.all",
                "GPN-MSA.LogisticRegression.chrom.subset_from_all",
                "CADD.LogisticRegression.chrom.subset_from_all",
                "Borzoi.LogisticRegression.chrom.subset_from_all",
                "CADD+GPN-MSA+Borzoi.LogisticRegression.chrom.subset_from_all",
            ],
        ),


rule complex_traits_by_gene:
    input:
        expand(
            "results/dataset/complex_traits_v22_matched_9/AUPRC_by_chrom_weighted_average/all/{model}.csv",
            model=[
                "GPN-MSA_absLLR.plus.score",
                "CADD.plus.RawScore",
                "Borzoi_L2_L2.plus.all",
                "GPN-MSA.LogisticRegression.chrom",
                "CADD.LogisticRegression.chrom",
                "Borzoi.LogisticRegression.chrom",
            ],
        ),


rule mendelian_traits_by_gene:
    input:
        expand(
            "results/dataset/mendelian_traits_v22_matched_9/AUPRC_by_chrom_weighted_average/all/{model}.csv",
            model=[
                "GPN-MSA_LLR.minus.score",
                "CADD.plus.RawScore",
                "Borzoi_L2_L2.plus.all",
                "GPN-MSA.LogisticRegression.chrom",
                "CADD.LogisticRegression.chrom",
                "Borzoi.LogisticRegression.chrom",
            ],
        ),


rule by_consequence:
    input:
        expand(
            "results/dataset/{dataset}/{metric}/{subset}/{model}.csv",
            dataset=config["datasets"],
            metric=[
                "AUPRC_by_chrom_weighted_average",
                "AUPRC",
            ],
            subset=config["consequence_subsets"],
            model=[
                "CADD.plus.RawScore",
                "Borzoi_L2_L2.plus.all",
                "GPN-MSA_LLR.minus.score",
                "GPN-MSA_absLLR.plus.score",
                "GPN_final_LLR.minus.score",
                "GPN_final_absLLR.plus.score",
                "GPN_final_Embeddings.plus.euclidean_distance",

                "evo2_1b_base_LLR.minus.score",
                "evo2_1b_base_absLLR.plus.score",
                "evo2_1b_base_Embeddings.plus.euclidean_distance",

                "evo2_7b_LLR.minus.score",
                "evo2_7b_absLLR.plus.score",
                "evo2_7b_Embeddings.plus.euclidean_distance",

                "evo2_40b_LLR.minus.score",
                "evo2_40b_absLLR.plus.score",
                "evo2_40b_Embeddings.plus.euclidean_distance",
            ],
        ),


rule genome_wide_consequences:
    input:
        expand(
            "results/simulated/chrom/{chrom}.annot.parquet",
            chrom=CHROMS,
        ),


rule de_novo:
    input:
        expand(
            "results/dataset/{dataset}/features/{features}.parquet",
            dataset=[
                #"de_novo_v1",
                #"de_novo_v2",
                #"de_novo_v3/5_prime_UTR_variant/9",
                #"de_novo_v3/3_prime_UTR_variant/9",
                #"de_novo_v3/upstream_gene_variant/9",
                #"de_novo_v3/non_coding_transcript_exon_variant/9",
                "de_novo_v4/9",
                "de_novo_v4_all",
            ],
            features=[
                #"phyloP-100v",
                #"phyloP-241m",
                #"phastCons-43p",
                "phyloP-100v_noimputation",
                "phyloP-241m_noimputation",
                "phastCons-43p_noimputation",
                "CADD_RawScore",
                "gpnmsa",
            ],
        )